In [27]:
import pandas as pd
df = pd.read_csv("/content/dataset-limpo2")

In [28]:
df

,defeito_constatado_id,solucao_id,familia_id,defeito_constatado_descricao,solucao_descricao,categoria_solucao,categoria_defeito,familia_descricao
0,26814.0,4982.0,5370.0,sem condições de manutenção no local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
1,26814.0,4982.0,5370.0,sem condições de manutenção no local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
2,26814.0,5227.0,7634.0,sem condições de manutenção no local,Cliente Recusou Atendimento,Orientação Cliente,Outros,Congelador
3,26814.0,5240.0,5370.0,sem condições de manutenção no local,Equipamento Recolhido,Troca Equipamento,Outros,Refrigerador
4,26814.0,5240.0,7634.0,sem condições de manutenção no local,Equipamento Recolhido,Troca Equipamento,Outros,Congelador
...,...,...,...,...,...,...,...,...
1440,60710.0,8517.0,5371.0,contaminado por motivo pragas,Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1441,60711.0,8517.0,5373.0,"contaminação cruzada (gordura, mofos e etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Chopeira
1442,60711.0,8517.0,5371.0,"contaminação cruzada (gordura, mofos e etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1443,60862.0,4984.0,5370.0,prateleira com defeito,Troca/Instalação De Prateleiras,Troca De Peça,Estrutura,Refrigerador
1444,60877.0,4982.0,5370.0,gabinete empenado,Solicitar Troca De Equipamento,Troca Equipamento,Estrutura,Refrigerador

In [29]:
df['defeito_constatado_descricao'] = df['defeito_constatado_descricao'].str.title()

In [30]:
df['familia_descricao'] = df['familia_descricao'].str.title()

In [31]:
df

,defeito_constatado_id,solucao_id,familia_id,defeito_constatado_descricao,solucao_descricao,categoria_solucao,categoria_defeito,familia_descricao
0,26814.0,4982.0,5370.0,Sem Condições De Manutenção No Local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
1,26814.0,4982.0,5370.0,Sem Condições De Manutenção No Local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
2,26814.0,5227.0,7634.0,Sem Condições De Manutenção No Local,Cliente Recusou Atendimento,Orientação Cliente,Outros,Congelador
3,26814.0,5240.0,5370.0,Sem Condições De Manutenção No Local,Equipamento Recolhido,Troca Equipamento,Outros,Refrigerador
4,26814.0,5240.0,7634.0,Sem Condições De Manutenção No Local,Equipamento Recolhido,Troca Equipamento,Outros,Congelador
...,...,...,...,...,...,...,...,...
1440,60710.0,8517.0,5371.0,Contaminado Por Motivo Pragas,Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1441,60711.0,8517.0,5373.0,"Contaminação Cruzada (Gordura, Mofos E Etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Chopeira
1442,60711.0,8517.0,5371.0,"Contaminação Cruzada (Gordura, Mofos E Etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1443,60862.0,4984.0,5370.0,Prateleira Com Defeito,Troca/Instalação De Prateleiras,Troca De Peça,Estrutura,Refrigerador
1444,60877.0,4982.0,5370.0,Gabinete Empenado,Solicitar Troca De Equipamento,Troca Equipamento,Estrutura,Refrigerador

In [32]:
df['solucao_descricao'].unique()

array(['Solicitar Troca De Equipamento', 'Cliente Recusou Atendimento',
       'Equipamento Recolhido', 'Cliente Não Autorizou',
       'Destravar Micromotor', 'Troca/Reparo Em Micro Motor',
       'Reparo Motor Evaporador', 'Troca De Hélice',
       'Carga De Gás Refrigerante', 'Troca De Capilar',
       'Troca De Filtro Secador', 'Troca Evaporador', 'Troca Condensador',
       'Visita Sta Com Troca De Peça',
       'Troca/Reparo Unidade De Refrigeração',
       'Troca/Reparo Unidade De Refrig', 'Troca De Unidade De Refrig',
       'Religar Contato/Tomada', 'Troca De Reator',
       'Troca De Transformador', 'Troca Da Fiação',
       'Revisão Geral No Sistema Elétrico',
       'Troca/Instalação De Prateleiras', 'Troca De Contato/Tomada',
       'Desativar Resistência', 'Regulagem De Porta',
       'Regulagem De Termostato', 'Troca De Termostato',
       'Ajuste Controlador', 'Troca De Compressor', 'Troca De Relé',
       'Troca Do Start', 'Troca De Sensor De Gelo',
       'Troca Do Sensor De Temperatura',
       'Reparo De Sensor De Temperatura', 'Nivelar Equipamento',
       'Reparo No Auto-Fechamento', 'Troca De Dreno', 'Troca De Gaxeta',
       'Troca Do Coletor', 'Posicionar Filtro Desidratador',
       'Limpeza No Dreno', 'Troca De Lâmpada', 'Troca De Fonte 12/24V',
       'Troca De Porta', 'Troca Do Puxador', 'Troca De Puxador',
       'Troca De Protetor Térmico', 'Troca Do Protetor De Lâmpada',
       'Ordem De Piso (Retrabalho)',
       'Ordem De Piso (Condenado Sem Conserto)', 'Troca De Capacitor',
       'Troca Do Controlador', 'Reparo De Controlador',
       'Reparo No Reator', 'Reparo Da Fonte 12/24 V', 'Ajuste No Led',
       'Reparo Na Fonte 12/24V', 'Troca De Grade Do Motor',
       'Reparo Na Gaxeta Da Porta', 'Reparo Na Gaxeta',
       'Troca De Prateleira', 'Ajuste De Canaleta', 'Troca Cabo De Força',
       'Troca De Adesivos', 'Troca Técnica', 'Troca Do Cabeamento',
       'Troca De Auto-Fechamento', 'Ajuste Do Pé Nivelador',
       'Troca De Pé Nivelador', 'Troca Do Pé Nivelador',
       'Limpar Condensador', 'Troca/Reparo Em Agitador',
       'Troca/Reparo Em Bomba De Recirculação',
       'Troca/Reparo Em Carbonatador', 'Troca De Carcaça/Filtro De Água',
       'Troca De Conector', 'Troca Da Fechadura',
       'Troca Mangueira De Alta Pressão', 'Troca De Solenoide',
       'Troca/Completar Nível Do Álcool', 'Troca De Cilindro De Co²',
       'Abrir Registro Do Cilindro De Co²',
       'Troca/Reparo Em Válvula Extratora',
       'Troca De Base Da Válvula Dispensadora',
       'Troca Mangueiras Xarope/Água', 'Troca De Espigão',
       'Troca/Reparo Válvula Dispensadora Ch', 'Aferição De Manômetro',
       'Troca/Reparo Em Bomba De Xarope', 'Sangrar Linha De Xarope/Água',
       'Troca Do Sensor De Condutividade',
       'Troca De Refil Do Filtro D Água', 'Abrir Registro De Água',
       'Troca/Reparo Regulador De Pressão', 'Troca De Resistência',
       'Troca Do Sensor De Nível', 'Sensor De Nível Com Defeito',
       'Troca/Reparo Em Serpentina', 'Troca/Reparo Em Válvula P Mix',
       'Trocar Bico Misturador/Difusor', 'Troca De Produto',
       'Sanitização', 'Trocar Água Do Gabinete',
       'Regular Proporção De Xarope', 'Pedido De Troca Do Produto',
       'Sem Condições De Reparo No Gabinete', 'Trocar Fusível',
       'Coleta De Água Para Análise', 'Troca/Reparo Em Botoeira',
       'Troca/Reparo Em Termostato', 'Desobstrução De Canaletas',
       'Troca/Reparo Suporte De Lâmpada', 'Reprogramação',
       'Troca/Reparo Sensor Temperatura', 'Troca/Reparo Sensor De Batida',
       'Troca/Reparo Em Moedeiro', 'Troca/Reparo Em Bill Acceptor',
       'Desobstrução Dos Aceitadores', 'Troca/Reparo Chicote Elétrico',
       'Troca/Reparo Em Contador', 'Troca/Reparo Na Placa Eletrônica',
       'Troca Do Display', 'Ajuste De Parâmetros',
       'Troca/Reparo Em Porta', 'Troca/Reparo Na Fechadura',
       'Troca Dos Indicadores De Sabor', 'Troca De Display',
       'Troca/Reparo Em Micro Switch', 'Troca/Reparo Em Home Sensor',
       'Troca/Reparo Conjunto De Corrente',
       'Troca De Refil Filtro De Água', 'Troca Do Plug',
       'Troca Do Pest Control', 'Regulagem Do Produto',
       'Falta De Retrolavagem', 'Retirada De Vazamento De Água',
       'Troca De Mangueiras', 'Falta De Água', 'Troca Do Motor De Insumo',
       'Reparo No Gabinete', 'Troca Da Carcaça Do Filtro',
       'Troca De Anel De Vedação', 'Troca Do Motor Batedor',
       'Troca Da Bomba De Café', 'Troca Da Bomba De Água',
       'Troca Do Filtro E Carga De Gás', 'Funilaria E Pintura', 'Reforma',
       'Pintura Geral', 'Pintura Interna', 'Pintura Externa',
       'Troca Da Placa', 'Troca Do Display E Placa',
       'Ajuste Nos Parâmetros', 'Ajuste Nos Parâmetros Do Controlador',
       'Troca Do Evaporador', 'Troca Do Evaporador E Filtro',
       'Sacar Produto Da Concorrência', 'Reciclagem Junto Ao Cliente',
       'Troca/Reparo De Extensão', 'Trocar Auto-Fechamento',
       'Troca De Cabeamento Do Termostato',
       'Troca/Ajuste Da Porta Ou Gaxeta', 'Troca De Controlador',
       'Troca De Evaporador E Filtro',
       'Trocar/Fixar Bandeja Do Evaporador', 'Troca Dreno',
       'Troca Do Painel', 'Troca Da Fonte 12/24 V', 'Reparo Na Porta',
       'Reparo Na Dobradiça', 'Reparo Em Lâmpada',
       'Recarga De Gás Refrigerante', 'Troca De Bandeja Do Evaporador',
       'Limpeza Do Condensador', 'Troca De Condensador',
       'Reparo No Condensador', 'Reparo Na Charola', 'Troca De Charola',
       'Orientação De Uso: Limpeza No Condensador',
       'Limpeza De Filtro Secador', 'Troca De Micromotor Do Condensador',
       'Troca De Micromotor Condensador',
       'Troca Hélice De Micromotor Condensador',
       'Troca De Micromotor Evaporador',
       'Troca Hélice De Micromotor Evaporador', 'Troca De Tubo Capilar',
       'Reparo No Tubo Capilar', 'Reparo De Sensor De Gelo',
       'Ajustes Nos Parâmetros',
       'Troca De Placa Eletrônica Do Controlador',
       'Reparo No Transformador', 'Troca De Fusível Do Termostato',
       'Reparo No Cabeamento Do Termostato',
       'Troca De Resistência Do Evaporador',
       'Reparo Na Resistência Do Evaporador',
       'Troca De Cabo Da Resistência', 'Reparo No Cabo Da Resistência',
       'Troca De Capacitor Do Condensador',
       'Troca De Cabo De Alimentação', 'Reparo No Cabo De Alimentação',
       'Orientação De Uso: Instalação Elétrica', 'Troca De Plug',
       'Conectar Plug', 'Troca De Cabo Do Display',
       'Reparo No Cabo Do Display',
       'Troca/Reparo Na Tomada (Cliente Responsável)',
       'Aterrar Equipamento', 'Troca De Interruptor De Aleta',
       'Reparo De Interruptor De Aleta', 'Troca De Protetor Da Lâmpada',
       'Reparo No Protetor Da Lâmpada', 'Reparo No Pé Nivelador',
       'Ajuste No Pé Nivelador', 'Troca De Adesivo',
       'Limpeza De Equipamento', 'Troca De Equipamento', 'Troca De Rele',
       'Reparo Na Prateleira', 'Reposição De Prateleira',
       'Ajuste No Gabinete', 'Troca De Grade Traseira Inferior',
       'Reparo Na Grade Traseira Inferior',
       'Troca De Grade Frontal Veneziana',
       'Reposição De Grade Frontal Veneziana',
       'Troca Na Bandeja Do Evaporador',
       'Reposição De Bandeja Do Evaporador',
       'Fixar Bandeja Do Evaporador',
       'Reparo Na Moldura Do Suporte Do Display',
       'Reparo Na Caixa De Proteção Do Display',
       'Reparo Na Caixa De Proteção Do Controlador Inferior', 'Sucateado',
       'Troca De Gaxeta Da Porta', 'Reparo No Puxador',
       'Troca De Dobradiça', 'Reparo No Dreno', 'Troca De Start',
       'Limpeza Do Evaporador', 'Troca De Tolva', 'Reparo Na Tolva',
       'Fixar Tolva', 'Fixar Grade Frontal Veneziana', 'Fixar Evaporador',
       'Fixar Condensador', 'Fixar Charola',
       'Fixar Micromotor Do Evaporador',
       'Fixar Micromotor Do Condensador', 'Reposição De Gaxeta',
       'Reposição De Puxador Da Porta', 'Reposição De Dobradiça',
       'Troca Da Resistência', 'Troca Motor Evaporador',
       'Ligar Na Tomada Com A Tensão Correta', 'Ajuste Da Hélice',
       'Fixar Motor Do Condensador', 'Troca Display',
       'Fixar Bandeja  Do Evaporador', 'Sangria No Sistema',
       'Troca Da Bomba De Circulação', 'Troca Ou Ajuste',
       'Descongelar A Máquina', 'Ajuste Do Controlador', 'Troca Da Peça',
       'Esgotar O Gabinete',
       'Fazer Sistema De Aterramento No Equipamento', 'Fazer Sanitização',
       'Defeito Sem Solução', 'Pequeno Retoque', 'Troca Do Filtro',
       'Troca Ou Ajuste No Fio', 'Troca Na Peça', 'Troca Da Plotagem',
       'Troca Da Gaxeta Ou Ajuste Da Porta', 'Necessidade De Sanitização',
       'Troca Do Chopp, Estragado', 'Troca Do Produto, Estragado',
       'Desamassado', 'Ajuste Da Válvula',
       'Regulagem Ou Troca Da Válvula', 'Ajuste No Sistema',
       'Sanitização Da Linha De Xarope',
       'Sanitização Da Linha De Água E Troca De Filtro',
       'Bloqueio Do Equipamento, E Comunicar O Cliente',
       'Equipamento Sanitizado'], dtype=object)

In [33]:
correcoes = {
    'Troca De Rele': 'Troca De Relé',

    'Troca De Fonte 12/24V': 'Troca Da Fonte 12/24 V',
    'Reparo Na Fonte 12/24V': 'Reparo Da Fonte 12/24 V',

    'Troca/Reparo Unidade De Refrig': 'Troca/Reparo Unidade De Refrigeração',
    'Troca De Unidade De Refrig': 'Troca/Reparo Unidade De Refrigeração'
}

df['solucao_descricao'] = df['solucao_descricao'].replace(correcoes)

In [34]:
df

,defeito_constatado_id,solucao_id,familia_id,defeito_constatado_descricao,solucao_descricao,categoria_solucao,categoria_defeito,familia_descricao
0,26814.0,4982.0,5370.0,Sem Condições De Manutenção No Local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
1,26814.0,4982.0,5370.0,Sem Condições De Manutenção No Local,Solicitar Troca De Equipamento,Troca Equipamento,Outros,Refrigerador
2,26814.0,5227.0,7634.0,Sem Condições De Manutenção No Local,Cliente Recusou Atendimento,Orientação Cliente,Outros,Congelador
3,26814.0,5240.0,5370.0,Sem Condições De Manutenção No Local,Equipamento Recolhido,Troca Equipamento,Outros,Refrigerador
4,26814.0,5240.0,7634.0,Sem Condições De Manutenção No Local,Equipamento Recolhido,Troca Equipamento,Outros,Congelador
...,...,...,...,...,...,...,...,...
1440,60710.0,8517.0,5371.0,Contaminado Por Motivo Pragas,Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1441,60711.0,8517.0,5373.0,"Contaminação Cruzada (Gordura, Mofos E Etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Chopeira
1442,60711.0,8517.0,5371.0,"Contaminação Cruzada (Gordura, Mofos E Etc...)",Equipamento Sanitizado,Limpeza,Sanitização / Contaminação,Post Mix
1443,60862.0,4984.0,5370.0,Prateleira Com Defeito,Troca/Instalação De Prateleiras,Troca De Peça,Estrutura,Refrigerador
1444,60877.0,4982.0,5370.0,Gabinete Empenado,Solicitar Troca De Equipamento,Troca Equipamento,Estrutura,Refrigerador

In [35]:
df['solucao_descricao'].unique()

array(['Solicitar Troca De Equipamento', 'Cliente Recusou Atendimento',
       'Equipamento Recolhido', 'Cliente Não Autorizou',
       'Destravar Micromotor', 'Troca/Reparo Em Micro Motor',
       'Reparo Motor Evaporador', 'Troca De Hélice',
       'Carga De Gás Refrigerante', 'Troca De Capilar',
       'Troca De Filtro Secador', 'Troca Evaporador', 'Troca Condensador',
       'Visita Sta Com Troca De Peça',
       'Troca/Reparo Unidade De Refrigeração', 'Religar Contato/Tomada',
       'Troca De Reator', 'Troca De Transformador', 'Troca Da Fiação',
       'Revisão Geral No Sistema Elétrico',
       'Troca/Instalação De Prateleiras', 'Troca De Contato/Tomada',
       'Desativar Resistência', 'Regulagem De Porta',
       'Regulagem De Termostato', 'Troca De Termostato',
       'Ajuste Controlador', 'Troca De Compressor', 'Troca De Relé',
       'Troca Do Start', 'Troca De Sensor De Gelo',
       'Troca Do Sensor De Temperatura',
       'Reparo De Sensor De Temperatura', 'Nivelar Equipamento',
       'Reparo No Auto-Fechamento', 'Troca De Dreno', 'Troca De Gaxeta',
       'Troca Do Coletor', 'Posicionar Filtro Desidratador',
       'Limpeza No Dreno', 'Troca De Lâmpada', 'Troca Da Fonte 12/24 V',
       'Troca De Porta', 'Troca Do Puxador', 'Troca De Puxador',
       'Troca De Protetor Térmico', 'Troca Do Protetor De Lâmpada',
       'Ordem De Piso (Retrabalho)',
       'Ordem De Piso (Condenado Sem Conserto)', 'Troca De Capacitor',
       'Troca Do Controlador', 'Reparo De Controlador',
       'Reparo No Reator', 'Reparo Da Fonte 12/24 V', 'Ajuste No Led',
       'Troca De Grade Do Motor', 'Reparo Na Gaxeta Da Porta',
       'Reparo Na Gaxeta', 'Troca De Prateleira', 'Ajuste De Canaleta',
       'Troca Cabo De Força', 'Troca De Adesivos', 'Troca Técnica',
       'Troca Do Cabeamento', 'Troca De Auto-Fechamento',
       'Ajuste Do Pé Nivelador', 'Troca De Pé Nivelador',
       'Troca Do Pé Nivelador', 'Limpar Condensador',
       'Troca/Reparo Em Agitador',
       'Troca/Reparo Em Bomba De Recirculação',
       'Troca/Reparo Em Carbonatador', 'Troca De Carcaça/Filtro De Água',
       'Troca De Conector', 'Troca Da Fechadura',
       'Troca Mangueira De Alta Pressão', 'Troca De Solenoide',
       'Troca/Completar Nível Do Álcool', 'Troca De Cilindro De Co²',
       'Abrir Registro Do Cilindro De Co²',
       'Troca/Reparo Em Válvula Extratora',
       'Troca De Base Da Válvula Dispensadora',
       'Troca Mangueiras Xarope/Água', 'Troca De Espigão',
       'Troca/Reparo Válvula Dispensadora Ch', 'Aferição De Manômetro',
       'Troca/Reparo Em Bomba De Xarope', 'Sangrar Linha De Xarope/Água',
       'Troca Do Sensor De Condutividade',
       'Troca De Refil Do Filtro D Água', 'Abrir Registro De Água',
       'Troca/Reparo Regulador De Pressão', 'Troca De Resistência',
       'Troca Do Sensor De Nível', 'Sensor De Nível Com Defeito',
       'Troca/Reparo Em Serpentina', 'Troca/Reparo Em Válvula P Mix',
       'Trocar Bico Misturador/Difusor', 'Troca De Produto',
       'Sanitização', 'Trocar Água Do Gabinete',
       'Regular Proporção De Xarope', 'Pedido De Troca Do Produto',
       'Sem Condições De Reparo No Gabinete', 'Trocar Fusível',
       'Coleta De Água Para Análise', 'Troca/Reparo Em Botoeira',
       'Troca/Reparo Em Termostato', 'Desobstrução De Canaletas',
       'Troca/Reparo Suporte De Lâmpada', 'Reprogramação',
       'Troca/Reparo Sensor Temperatura', 'Troca/Reparo Sensor De Batida',
       'Troca/Reparo Em Moedeiro', 'Troca/Reparo Em Bill Acceptor',
       'Desobstrução Dos Aceitadores', 'Troca/Reparo Chicote Elétrico',
       'Troca/Reparo Em Contador', 'Troca/Reparo Na Placa Eletrônica',
       'Troca Do Display', 'Ajuste De Parâmetros',
       'Troca/Reparo Em Porta', 'Troca/Reparo Na Fechadura',
       'Troca Dos Indicadores De Sabor', 'Troca De Display',
       'Troca/Reparo Em Micro Switch', 'Troca/Reparo Em Home Sensor',
       'Troca/Reparo Conjunto De Corrente',
       'Troca De Refil Filtro De Água', 'Troca Do Plug',
       'Troca Do Pest Control', 'Regulagem Do Produto',
       'Falta De Retrolavagem', 'Retirada De Vazamento De Água',
       'Troca De Mangueiras', 'Falta De Água', 'Troca Do Motor De Insumo',
       'Reparo No Gabinete', 'Troca Da Carcaça Do Filtro',
       'Troca De Anel De Vedação', 'Troca Do Motor Batedor',
       'Troca Da Bomba De Café', 'Troca Da Bomba De Água',
       'Troca Do Filtro E Carga De Gás', 'Funilaria E Pintura', 'Reforma',
       'Pintura Geral', 'Pintura Interna', 'Pintura Externa',
       'Troca Da Placa', 'Troca Do Display E Placa',
       'Ajuste Nos Parâmetros', 'Ajuste Nos Parâmetros Do Controlador',
       'Troca Do Evaporador', 'Troca Do Evaporador E Filtro',
       'Sacar Produto Da Concorrência', 'Reciclagem Junto Ao Cliente',
       'Troca/Reparo De Extensão', 'Trocar Auto-Fechamento',
       'Troca De Cabeamento Do Termostato',
       'Troca/Ajuste Da Porta Ou Gaxeta', 'Troca De Controlador',
       'Troca De Evaporador E Filtro',
       'Trocar/Fixar Bandeja Do Evaporador', 'Troca Dreno',
       'Troca Do Painel', 'Reparo Na Porta', 'Reparo Na Dobradiça',
       'Reparo Em Lâmpada', 'Recarga De Gás Refrigerante',
       'Troca De Bandeja Do Evaporador', 'Limpeza Do Condensador',
       'Troca De Condensador', 'Reparo No Condensador',
       'Reparo Na Charola', 'Troca De Charola',
       'Orientação De Uso: Limpeza No Condensador',
       'Limpeza De Filtro Secador', 'Troca De Micromotor Do Condensador',
       'Troca De Micromotor Condensador',
       'Troca Hélice De Micromotor Condensador',
       'Troca De Micromotor Evaporador',
       'Troca Hélice De Micromotor Evaporador', 'Troca De Tubo Capilar',
       'Reparo No Tubo Capilar', 'Reparo De Sensor De Gelo',
       'Ajustes Nos Parâmetros',
       'Troca De Placa Eletrônica Do Controlador',
       'Reparo No Transformador', 'Troca De Fusível Do Termostato',
       'Reparo No Cabeamento Do Termostato',
       'Troca De Resistência Do Evaporador',
       'Reparo Na Resistência Do Evaporador',
       'Troca De Cabo Da Resistência', 'Reparo No Cabo Da Resistência',
       'Troca De Capacitor Do Condensador',
       'Troca De Cabo De Alimentação', 'Reparo No Cabo De Alimentação',
       'Orientação De Uso: Instalação Elétrica', 'Troca De Plug',
       'Conectar Plug', 'Troca De Cabo Do Display',
       'Reparo No Cabo Do Display',
       'Troca/Reparo Na Tomada (Cliente Responsável)',
       'Aterrar Equipamento', 'Troca De Interruptor De Aleta',
       'Reparo De Interruptor De Aleta', 'Troca De Protetor Da Lâmpada',
       'Reparo No Protetor Da Lâmpada', 'Reparo No Pé Nivelador',
       'Ajuste No Pé Nivelador', 'Troca De Adesivo',
       'Limpeza De Equipamento', 'Troca De Equipamento',
       'Reparo Na Prateleira', 'Reposição De Prateleira',
       'Ajuste No Gabinete', 'Troca De Grade Traseira Inferior',
       'Reparo Na Grade Traseira Inferior',
       'Troca De Grade Frontal Veneziana',
       'Reposição De Grade Frontal Veneziana',
       'Troca Na Bandeja Do Evaporador',
       'Reposição De Bandeja Do Evaporador',
       'Fixar Bandeja Do Evaporador',
       'Reparo Na Moldura Do Suporte Do Display',
       'Reparo Na Caixa De Proteção Do Display',
       'Reparo Na Caixa De Proteção Do Controlador Inferior', 'Sucateado',
       'Troca De Gaxeta Da Porta', 'Reparo No Puxador',
       'Troca De Dobradiça', 'Reparo No Dreno', 'Troca De Start',
       'Limpeza Do Evaporador', 'Troca De Tolva', 'Reparo Na Tolva',
       'Fixar Tolva', 'Fixar Grade Frontal Veneziana', 'Fixar Evaporador',
       'Fixar Condensador', 'Fixar Charola',
       'Fixar Micromotor Do Evaporador',
       'Fixar Micromotor Do Condensador', 'Reposição De Gaxeta',
       'Reposição De Puxador Da Porta', 'Reposição De Dobradiça',
       'Troca Da Resistência', 'Troca Motor Evaporador',
       'Ligar Na Tomada Com A Tensão Correta', 'Ajuste Da Hélice',
       'Fixar Motor Do Condensador', 'Troca Display',
       'Fixar Bandeja  Do Evaporador', 'Sangria No Sistema',
       'Troca Da Bomba De Circulação', 'Troca Ou Ajuste',
       'Descongelar A Máquina', 'Ajuste Do Controlador', 'Troca Da Peça',
       'Esgotar O Gabinete',
       'Fazer Sistema De Aterramento No Equipamento', 'Fazer Sanitização',
       'Defeito Sem Solução', 'Pequeno Retoque', 'Troca Do Filtro',
       'Troca Ou Ajuste No Fio', 'Troca Na Peça', 'Troca Da Plotagem',
       'Troca Da Gaxeta Ou Ajuste Da Porta', 'Necessidade De Sanitização',
       'Troca Do Chopp, Estragado', 'Troca Do Produto, Estragado',
       'Desamassado', 'Ajuste Da Válvula',
       'Regulagem Ou Troca Da Válvula', 'Ajuste No Sistema',
       'Sanitização Da Linha De Xarope',
       'Sanitização Da Linha De Água E Troca De Filtro',
       'Bloqueio Do Equipamento, E Comunicar O Cliente',
       'Equipamento Sanitizado'], dtype=object)

In [36]:
df["categoria_defeito"] = df["categoria_defeito"].replace(
    "eletrônico",
    "Eletrônico"
)

df = df[
    df["categoria_defeito"] !=
    "À medida que avalanche de produtos químicos avançava, a maioria já estava absorvida."
]

df["categoria_defeito"] = df["categoria_defeito"].replace(
    "Moedeiro /",
    "Moedeiro"
)

In [37]:
"À medida que avalanche de produtos químicos avançava, a maioria já estava absorvida." in df["categoria_defeito"].values

False

In [38]:
df["familia_descricao"] = df["familia_descricao"].replace(
    "Maquina De Cafe",
    "Máquina de Café"
)

In [40]:
df.to_csv('dataset-limpo-projeto.csv', index=False)

In [41]:
from google.colab import files

files.download("dataset-limpo-projeto.csv")